### ISSUE TITLE
请问您的代码可以得出论文中的数据吗

### ISSUE THREAD

**Issue by Wangqin9610** [Pea-Shooter/AHDRNet#1]
谢谢

**Comment by liuzhen03** [comment]
可以

**Comment by LiuzhuForFun** [comment]
> 谢谢

请问，您复现出来了吗

**Comment by Wangqin9610** [comment]
复现出来了 


| |
王琴
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年8月23日 ***@***.***> 写道：

谢谢

请问，您复现出来了吗

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
