### ISSUE TITLE
How to save the inference results (png or hdr formation)?

### ISSUE THREAD

**Issue by LiuzhuForFun** [Pea-Shooter/AHDRNet#2]
Thanks for your reproduce!
I wonder that, the final result is clampped between 0 and 1.
How to obtain the final result, such as the tonemap/ u-law or hdr formation?

**Comment by liuzhen03** [comment]
I will add the code later

**Comment by ReckonerInheritor** [comment]
，


---Original---
From: &quot;Zhen ***@***.***&gt;
Date: Fri, Jun 18, 2021 12:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Pea-Shooter/AHDRNet] How to save the inference results (png or hdr formation)? (#2)




 
I will add the code later
 
&mdash;

**Comment by liuzhen03** [comment]
The code can be found in [https://github.com/liuzhen03/ADNet/blob/main/utils/utils.py](here).
