### ISSUE TITLE
How to reproduce the results of the paper?

### ISSUE THREAD

**Issue by lguduy** [Pea-Shooter/AHDRNet#3]
Hi. Thanks for your great work!
I set lr=1e-4, batch_size=4, train 4000 epochs, but the PSNR or SSIM is worse than that in the paper. Can you give more train details. Thanks!

**Comment by liuzhen03** [comment]
All settings are the same as the original paper except for the lr=1e-4 and bs=16, can you tell the specific values of your PSNR and SSIM?

**Comment by ReckonerInheritor** [comment]
11111，吧1111啊！


---Original---
From: &quot;Zhen ***@***.***&gt;
Date: Fri, Jun 18, 2021 12:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Pea-Shooter/AHDRNet] How to reproduce the results of the paper? (#3)




 
All settings are the same as the original paper except for the lr=1e-4 and bs=16, can you tell the specific values of your PSNR and SSIM?
 
&mdash;

**Comment by lguduy** [comment]
> All settings are the same as the original paper except for the lr=1e-4 and bs=16, can you tell the specific values of your PSNR and SSIM?

Thanks for your reply. I checked my code and found a bug in data preprocess, I will train using your settings. And lr_decay_interval you set?

**Comment by LiuzhuForFun** [comment]
> > All settings are the same as the original paper except for the lr=1e-4 and bs=16, can you tell the specific values of your PSNR and SSIM?
> 
> Thanks for your reply. I checked my code and found a bug in data preprocess, I will train using your settings. And lr_decay_interval you set?

@lguduy What the PSNR and SSIM you finally obtained?
