### ISSUE TITLE
Why the denselayers is 5?

### ISSUE THREAD

**Issue by ZhengLingxiang** [Pea-Shooter/AHDRNet#4]
Hi, i have a question that why the denselayer setting in your code is 5 but the source code of author is 6?

**Comment by LiuzhuForFun** [comment]
@ZhengLingxiang Hi，do you get the orginal results as the paper reported?

**Comment by ZhengLingxiang** [comment]
@LiuzhuForFun i cann't reproduce the same result as shown in the paper. The result still contain some artifacts.

**Comment by LiuzhuForFun** [comment]
Same concern.  Is three some efficient re-implementation for HDR constrcution? @ZhengLingxiang

**Comment by LiuzhuForFun** [comment]
@ZhengLingxiang 你训练到多少了，我PSNR刚到43

**Comment by ZhengLingxiang** [comment]
@LiuzhuForFun 10000ep，不到43

**Comment by LiuzhuForFun** [comment]
@ZhengLingxiang 这么pytorch多代码，没找到一个很好的复现

**Comment by liuzhen03** [comment]
> Hi, i have a question that why the denselayer setting in your code is 5 but the source code of author is 6?

Because setting it to 6 doesn't work for me.

**Comment by LiuzhuForFun** [comment]
@ZhengLingxiang @liuzhen03  Hi, thanks for your codes! I have met a problem, it is hard to be convergent when changes the network architecture. The psnr of validation is always between 7 dB, that means it is not work. Could you please to provide some suggestions? I wonder, it is also the reason setting it to 6 is not work. Thanks, I hope we can concat and address it, thanks
