### ISSUE TITLE
logx

### ISSUE THREAD

**Issue by Qirui-Y** [Pea-Shooter/AHDRNet#5]
Your code is great. Can you provide the corresponding requirement.txt? Because I have some environmental problems during the reproduction process, such as logx.

**Comment by liuzhen03** [comment]
Thanks. 
1. The `logx` is a module of `runx`, which is an experiments management tool provided by NVIDIA. Feel free to ignore it if it puzzles you. 
2. You can get the requirement.txt from our recent work [ADNet](https://github.com/liuzhen03/ADNet).

**Comment by Qirui-Y** [comment]
邮件可能无法及时回复，如有查收会尽快回复您。
