### ISSUE TITLE
请问您复现出原论文的结果了吗

### ISSUE THREAD

**Issue by Wanglongzhi2001** [Pea-Shooter/AHDRNet#7]
我按照您的代码，仅仅只是改动了logx部分，但是没能得到理想的结果，所以想请问是我的问题还是本来复现不出来原论文结果

**Comment by NixNait** [comment]
> 我按照您的代码，仅仅只是改动了logx部分，但是没能得到理想的结果，所以想请问是我的问题还是本来复现不出来原论文结果

您好，请问您复现出来了吗

**Comment by Wanglongzhi2001** [comment]
> > 我按照您的代码，仅仅只是改动了logx部分，但是没能得到理想的结果，所以想请问是我的问题还是本来复现不出来原论文结果
> 
> 您好，请问您复现出来了吗

复现了
